// Copyright 2017-2026 @pezkuwi/keyring authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev
// (packageInfo imports will be kept as-is, user-editable)

import { detectPackage } from '@pezkuwi/util';
import { packageInfo as utilInfo } from '@pezkuwi/util/packageInfo';
import { packageInfo as cryptoInfo } from '@pezkuwi/util-crypto/packageInfo';

import { packageInfo } from './packageInfo.js';

detectPackage(packageInfo, null, [cryptoInfo, utilInfo]);
