// Copyright 2017-2026 @pezkuwi/util authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev
// (packageInfo imports will be kept as-is, user-editable)

import { packageInfo as decoderInfo } from '@pezkuwi/x-textdecoder';
import { packageInfo as encoderInfo } from '@pezkuwi/x-textencoder';

import { detectPackage } from './detectPackage.js';
import { packageInfo } from './packageInfo.js';

detectPackage(packageInfo, null, [decoderInfo, encoderInfo]);
