// Copyright 2017-2025 @polkadot/hw-ledger authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev
// (packageInfo imports will be kept as-is, user-editable)

import { packageInfo as transportInfo } from '@pezkuwi/hw-ledger-transports/packageInfo';
import { detectPackage } from '@pezkuwi/util';
import { packageInfo as utilInfo } from '@pezkuwi/util/packageInfo';

import { packageInfo } from './packageInfo.js';

detectPackage(packageInfo, null, [transportInfo, utilInfo]);
