// Copyright 2017-2026 @pezkuwi/x-fetch authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev

export const packageInfo = { name: '@pezkuwi/x-fetch', path: 'auto', type: 'auto', version: '14.0.10' };
